kind: Pod
apiVersion: v1
metadata:
        name: demo-pod1
spec:
        containers:
              - name: container1
                image: nginx
                ports: 
                     - containerPort: 80
