apiVersion: apps/v1
kind: Deployment
metadata: 
    name: pythonapp-demo
    labels:
        app: python
spec:
    replicas: 2
    selector: 
        matchLabels:
              app: python
    minReadySeconds: 5
    strategy:
         type: RollingUpdate
         rollingUpdate:
               maxSurge: 2
               maxUnavailable: 1
    template:
         metadata:
            labels: 
               app: python
         spec:
             containers:
             - name: pythonapp
               image: amishtm/pythonapp:latest
               ports:
               - containerPort: 5000
               readinessProbe:
                   httpGet:
                     path: /    
                     port: 5000
                   initialDelaySeconds: 5
                   periodSeconds: 5
                   successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
        name: pythonapp-service
spec: 
  selector:
          app: python
  type: NodePort
  ports:
     - port: 5000
       targetPort: 5000
       nodePort: 32500

